#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Convert a monospace BDF font to an idfxx::font::mono_font C++ source file.

Usage:
    bdf_to_c.py FONT.bdf IDENTIFIER [HEADER] > out.cpp

HEADER is the header included by the generated file (default: idfxx/font.hpp).
It must declare `extern const mono_font IDENTIFIER;` in namespace idfxx::font,
so the generated definition gets external linkage.

Only the printable ASCII range (0x20-0x7E) is emitted. Each glyph is stored
row-major, MSB-first, ceil(cell_width / 8) bytes per row, cell_height rows.
"""

import re
import sys

FIRST_CHAR = 0x20
LAST_CHAR = 0x7E


def parse_bdf(path):
    with open(path) as f:
        lines = f.read().splitlines()

    fbb = None  # (w, h, xoff, yoff)
    comment = []
    glyphs = {}  # encoding -> (bbx, rows)

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("COMMENT"):
            comment.append(line[len("COMMENT") :].strip())
        elif line.startswith("FONTBOUNDINGBOX"):
            fbb = tuple(int(v) for v in line.split()[1:5])
        elif line.startswith("STARTCHAR"):
            encoding = None
            bbx = None
            rows = []
            i += 1
            while i < len(lines) and not lines[i].startswith("ENDCHAR"):
                l = lines[i]
                if l.startswith("ENCODING"):
                    encoding = int(l.split()[1])
                elif l.startswith("BBX"):
                    bbx = tuple(int(v) for v in l.split()[1:5])
                elif l.startswith("BITMAP"):
                    i += 1
                    while i < len(lines) and not lines[i].startswith("ENDCHAR"):
                        rows.append(int(lines[i], 16))
                        i += 1
                    i -= 1
                i += 1
            if encoding is not None and FIRST_CHAR <= encoding <= LAST_CHAR:
                glyphs[encoding] = (bbx, rows)
        i += 1

    if fbb is None:
        sys.exit("error: no FONTBOUNDINGBOX")
    return fbb, comment, glyphs


def render_glyph(fbb, bbx, rows):
    """Places a glyph's BBX bitmap into the full font cell.

    Returns cell_height rows of cell-wide bits (as ints, MSB = leftmost
    pixel, left-aligned in ceil(cell_w/8) bytes).
    """
    cell_w, cell_h, cell_xoff, cell_yoff = fbb
    bbx_w, bbx_h, bbx_xoff, bbx_yoff = bbx if bbx else (cell_w, cell_h, cell_xoff, cell_yoff)

    ascent = cell_h + cell_yoff
    top_row = ascent - (bbx_h + bbx_yoff)
    xshift = bbx_xoff - cell_xoff

    src_bytes = (bbx_w + 7) // 8
    dst_bytes = (cell_w + 7) // 8

    cell = [0] * cell_h
    for r, row in enumerate(rows):
        y = top_row + r
        if 0 <= y < cell_h:
            # Left-align the row in the source byte width, then shift into place.
            bits = row << (dst_bytes * 8 - src_bytes * 8) if dst_bytes >= src_bytes else row
            cell[y] = (bits >> xshift) & ((1 << (dst_bytes * 8)) - 1)
    return cell


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit(__doc__)
    path, ident = sys.argv[1], sys.argv[2]
    header = sys.argv[3] if len(sys.argv) == 4 else "idfxx/font.hpp"

    fbb, comment, glyphs = parse_bdf(path)
    cell_w, cell_h = fbb[0], fbb[1]
    dst_bytes = (cell_w + 7) // 8

    out = []
    out.append("// Generated by scripts/bdf_to_c.py — DO NOT EDIT.")
    out.append(f"// Source: {path.split('/')[-1]}")
    for c in comment:
        if c and not c.startswith("*/") and not c.startswith("/*"):
            out.append(f"// {c.lstrip('* ')}".rstrip())
    out.append("")
    out.append(f"#include <{header}>")
    out.append("")
    out.append("namespace idfxx::font {")
    out.append("")
    out.append("namespace {")
    out.append("")
    out.append("// clang-format off")
    out.append(f"constexpr unsigned char {ident}_bitmap[] = {{")

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        bbx, rows = glyphs.get(code, (None, []))
        cell = render_glyph(fbb, bbx, rows)
        label = chr(code) if chr(code) != "\\" else "backslash"
        row_bytes = []
        for row in cell:
            for b in range(dst_bytes - 1, -1, -1):
                row_bytes.append(f"0x{(row >> (b * 8)) & 0xFF:02X}")
        out.append(f"    // 0x{code:02X} '{label}'")
        out.append("    " + ", ".join(row_bytes) + ",")

    out.append("};")
    out.append("// clang-format on")
    out.append("")
    out.append("} // namespace")
    out.append("")
    out.append(f"const mono_font {ident}{{")
    out.append(f"    .width = {cell_w},")
    out.append(f"    .height = {cell_h},")
    out.append(f"    .first_char = 0x{FIRST_CHAR:02X},")
    out.append(f"    .last_char = 0x{LAST_CHAR:02X},")
    out.append(f"    .bitmap = {ident}_bitmap,")
    out.append("};")
    out.append("")
    out.append("} // namespace idfxx::font")
    print("\n".join(out))


if __name__ == "__main__":
    main()
